### ISSUE TITLE
Use of component scan in an auto-configuration is quite unusual 

### ISSUE THREAD

**Issue by snicoll** [savantly-net/sprout-spring-boot-starter#1]
Could you please reconsider removing `@ComponentScan` [in the auto-configuration](https://github.com/savantly-net/sprout-spring-boot-starter/blob/08923497658b7d9cdd90fa53e4ea3077618da72b/src/main/java/net/savantly/sprout/autoconfigure/SproutAutoConfigure.java#L20) and replace that with dedicated `@Bean` configuration?

It is very unusual to use component scan there.

**Comment by jdbranham** [comment]
fixed by 5f80bd55002c88a982c9092a0edbb6f72fdc3b66
